package dev.esxiclient.app.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF1B6B52)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA4F2D3)
val md_theme_light_onPrimaryContainer = Color(0xFF002117)
val md_theme_light_secondary = Color(0xFF4E6355)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD0E8D6)
val md_theme_light_onSecondaryContainer = Color(0xFF0B1F15)
val md_theme_light_tertiary = Color(0xFF3C6472)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC0E9FA)
val md_theme_light_onTertiaryContainer = Color(0xFF001F28)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFDF8)
val md_theme_light_onBackground = Color(0xFF191C1A)
val md_theme_light_surface = Color(0xFFFBFDF8)
val md_theme_light_onSurface = Color(0xFF191C1A)
val md_theme_light_surfaceVariant = Color(0xFFDDE5DB)
val md_theme_light_onSurfaceVariant = Color(0xFF414942)
val md_theme_light_outline = Color(0xFF717972)
val md_theme_light_outlineVariant = Color(0xFFC1C9C0)

val md_theme_dark_primary = Color(0xFF88D6B7)
val md_theme_dark_onPrimary = Color(0xFF003826)
val md_theme_dark_primaryContainer = Color(0xFF00513A)
val md_theme_dark_onPrimaryContainer = Color(0xFFA4F2D3)
val md_theme_dark_secondary = Color(0xFFB4CCBB)
val md_theme_dark_onSecondary = Color(0xFF20352A)
val md_theme_dark_secondaryContainer = Color(0xFF374B3F)
val md_theme_dark_onSecondaryContainer = Color(0xFFD0E8D6)
val md_theme_dark_tertiary = Color(0xFFA4CDDE)
val md_theme_dark_onTertiary = Color(0xFF053542)
val md_theme_dark_tertiaryContainer = Color(0xFF234C59)
val md_theme_dark_onTertiaryContainer = Color(0xFFC0E9FA)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1A)
val md_theme_dark_onBackground = Color(0xFFE1E3DE)
val md_theme_dark_surface = Color(0xFF191C1A)
val md_theme_dark_onSurface = Color(0xFFE1E3DE)
val md_theme_dark_surfaceVariant = Color(0xFF414942)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C9C0)
val md_theme_dark_outline = Color(0xFF8B938B)
val md_theme_dark_outlineVariant = Color(0xFF414942)

val StatusGreen = Color(0xFF4CAF50)
val StatusRed = Color(0xFFF44336)
val StatusOrange = Color(0xFFFF9800)
val StatusGray = Color(0xFF9E9E9E)
